name: Auto Version Demo

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:

      # 1) Checkout your code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Run GitVersion via the official Action
      - name: Calculate version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.0
        with:
          # optional: default to ContinuousDelivery mode
          mode: ContinuousDelivery

      # 3) Show the computed version in the logs
      - name: Log version
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "Major:      ${{ steps.gitversion.outputs.major }}"
          echo "Minor:      ${{ steps.gitversion.outputs.minor }}"
          echo "Patch:      ${{ steps.gitversion.outputs.patch }}"
          echo "Commits:    ${{ steps.gitversion.outputs.commitsSinceVersionSource }}"

      # 4) Add version to the run summary
      - name: Add to run summary
        run: |
          echo "## 📦 Build Version" >> $GITHUB_STEP_SUMMARY
          echo "- **FullSemVer:** `${{ steps.gitversion.outputs.fullSemVer }}`" \
            >> $GITHUB_STEP_SUMMARY

      # 5) Build & run your demo app
      - name: Build & run DemoApp
        working-directory: DemoApp
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet run --no-build
