name: Auto Version Demo

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your repo
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Install .NET 9 so you can build net9.0 projects
      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      # 3) Install GitVersion (v6) on the runner
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.x'

      # 4) Calculate the version
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4

      # 5) Publish it in the run Summary
      - name: Add version to run summary
        run: |
          echo "## 📦 Build Version" >> $GITHUB_STEP_SUMMARY
          echo "- **FullSemVer:** \`${{ steps.gitversion.outputs.fullSemVer }}\`" \
            >> $GITHUB_STEP_SUMMARY

      # 6) Build & run your net9.0 DemoApp
      - name: Build & run DemoApp
        working-directory: DemoApp
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet run --no-build
